### ISSUE TITLE
Testplan server release 10.7.0

### ISSUE THREAD

**Issue by jnweiger** [jnweiger/issue-test#5]
# ownCloud Server Minor Release Checklist

Most checklist items are meant to be actioned in the given order. In some cases tasks can be parallelized.
For some items, a fixed timing is important. E.g. customer communication is 2 weeks ahead of the release.
When raising tickets for specific sub-tasks, please add a link to said ticket by editing this release ticket.
Items that do not mention anybody are done by the BTR team members @HanaGemela @jnweiger @davitol

The progress of all release tickets is tracked in the releases board https://github.com/orgs/owncloud/projects/20 .
Whenever QA suggests a fix, the release ticket goes back to 'In dev'. The next beta/RC starts when it again reaches 'dev done/RC needed'.

## Pre-Release Phase

- [ ] DEV: Paste this template into a github release ticket in owncloud/enterprise - @micbar
- [ ] DEV: Create a new GitHub Release project in ownCloud orga, move tickets there - @micbar
- [ ] DEV: Check status of last translation job https://drone.owncloud.com/owncloud/translation-sync/ - @dschmidt, @micbar, @jnweiger
- [ ] DEV: Check PHP dependency updates - @micbar @pdavis
- [ ] DEV: Check for any "[Test-only]" updates - @pdavis @individualIT
- [ ] DEV: [Create a preview of the changelog](https://confluence.owncloud.com/display/OG/Generating+Changelog+Entries) in core, post below in release ticket, highlight items related to clients - @micbar
- [ ] QA: Estimate QA efforts - @davitol, @jnweiger, @jesmrec, @HanaGemela
- [ ] SECURITY: prepare advisories to be ready two weeks before estimated release - @c0rby
- [ ] BTR: Release kickoff meeting (Specify release schedule, roles, beta communication) - @micbar, @pmaier1, @jnweiger, @jesmrec, @HanaGemela, @frankaellen, @davitol

- [ ] COMMUNICATION: public announcement of start of beta phase, estimated timeline - @frankaellen
- [ ] COMMUNICATION: Central posting: in a few days, expect beta. Please subscribe here - @jnweiger

## Beta Phase (skip for patch releases)

- [ ] DEV: tag the beta in github (no release branch) - @micbar
- [ ] BTR: [Build the beta](https://confluence.owncloud.com/display/OG/Releasing+ownCloud+Server#ReleasingownCloudServer-CommunityTarballs)
- [ ] BTR: Create [docker images](https://confluence.owncloud.com/display/OG/Creating+Docker+Image)
- [ ] DEV: Update Changelog in release ticket (Highlight updates and new client related items) - @micbar, @jnweiger

- [ ] QA: Smoke tests complete tarball (link to test plan / docs) - @davitol

- [ ] COMMUNICATION: Ping Marketing: beta communication and links
- [ ] COMMUNICATION: Details - @frankaellen
	- [ ] Add beta phase on /beta-testing webpage - @frankaellen
	- [ ] Send newsletter to beta & testing subscribers list - @frankaellen
	- [ ] Announce the release on central, [Category News, Tag server](https://central.owncloud.org/tags/c/news/server) - @jnweiger, @HanaGemela
	- [ ] Forward central link to eng + release-coordination mailing lists - @jnweiger, @HanaGemela

- [ ] QA: (_optional_) Changelog testing (create QA ticket with changelog items) - @davitol
- [ ] QA: (_optional_) Changelog testing against desktop client - @HanaGemela
- [ ] QA: (_optional_) Changelog testing against mobile clients - @jesmrec

- [ ] If "good enough": - @HanaGemela, @jnweiger
	- [ ] BUILD: Build and publish Linux packages for beta in testing repo, then email to eng + release-coordination mailing lists - @crrodriguez
	- [ ] PUBLISH: Adjust [web update server] to deliver releases and test - @VicDeo, @davitol
		- [ ] Create or update PR to point web update server "beta" channel - @VicDeo, @davitol
		- [ ] QA: test update PR - @davitol
		- [ ] PUBLISH: Deploy [web update server] to deliver releases - @crrodriguez
- [ ] MGMT: If code was changed: add (shortened) checklist section for next Beta here

## RC Phase

- [ ] SECURITY: Make sure [revocation list](https://github.com/owncloud/handbook/issues/76) for app keys have been merged - @c0rby @micbar
- [ ] SECURITY: Update [shipped ca-certificates](https://github.com/owncloud/handbook/issues/76) - @c0rby @micbar
- [ ] DEV: Create release branch `release-$version` from master (the last beta tag or later) - @micbar
	- [ ] Feature freeze. All release-related fixes of to the release branch - @micbar
- [ ] DEV: [Move changelog/unreleased/* files and create preview](https://confluence.owncloud.com/display/OG/Generating+Changelog+Entries) in release branch - @micbar
	- [ ] Update Changelog in release ticket. (Highlight updates and new client related items) - @micbar, @jnweiger
- [ ] DOCS: Provide technical information on which versions of the desktop sync client and mobile clients are compatible/recommended - @michaelstingl
- [ ] DOCS: Prepare, merge and deploy release notes - @pmaier1
- [ ] DOCS: Update version number in various places - @pmaier1
- [ ] BTR: [Build RC](https://confluence.owncloud.com/display/OG/Releasing+ownCloud+Server#ReleasingownCloudServer-CommunityTarballs)
- [ ] BTR: Create [docker images](https://confluence.owncloud.com/display/OG/Creating+Docker+Image)
- [ ] QA: Smoke tests complete tarball (link to test plan / docs) - @davitol

- [ ] SECURITY: run RIPS scanner - @c0rby @micbar @IljaN
- [ ] SECURITY: [prepare advisories](https://github.com/owncloud/handbook/issues/77) - @c0rby @micbar @IljaN

- [ ] COMMUNICATION: Ping Marketing: RC communication, feature freeze, and links.
- [ ] COMMUNICATION: Details - @frankaellen
	- [ ] Add beta phase on /beta-testing webpage - @frankaellen
	- [ ] Send newsletter to beta & testing subscribers list - @frankaellen
	- [ ] Announce release (and feature freeze) on central, [Category News, Tag server](https://central.owncloud.org/tags/c/news/server) - @jnweiger, @HanaGemela
	- [ ] Forward central link to eng + release-coordination mailing lists - @jnweiger, @HanaGemela

- [ ] QA: Changelog testing (create or update QA ticket with changelog items) - @davitol
- [ ] QA: Changelog testing against desktop client - @HanaGemela
- [ ] QA: Changelog testing against mobile clients - @jesmrec

- [ ] MGMT: If "good enough":
	- [ ] BUILD: Build and publish Linux packages for RC in testing repo, then email to eng + release-coordination mailing lists - @crrodriguez
	- [ ] PUBLISH: Adjust [web update server] to deliver releases and test - @VicDeo @davitol
		- [ ] Create or update PR to point web update server "beta" channel - @VicDeo
		- [ ] QA: test update PR - @davitol
		- [ ] PUBLISH: Deploy [web update server] to deliver releases - @crrodriguez
- [ ] MGMT: If code was changed: add (shortened) checklist section for next RC here

## Final Phase

- [ ] BTR: [Build final release](https://confluence.owncloud.com/display/OG/Releasing+ownCloud+Server#ReleasingownCloudServer-CommunityTarballs)
- [ ] BTR: Build Linux packages (do not yet publish) - @crrodriguez, @jnweiger
- [ ] QA: Smoke test complete tarball - @davitol
- [ ] QA: Smoke test desktop client - @HanaGemela
- [ ] QA: Smoke test mobile clients - @jesmrec
- [ ] PUBLISH: [Upload the tarballs for customers into portals](https://confluence.owncloud.com/display/OG/Releasing+ownCloud+Server#ReleasingownCloudServer-CommunityTarballs)
- [ ] PUBLISH: Update the link to the latest tarballs on the [mirrors](https://gitea.owncloud.services/devops/mirrors/src/branch/master/ansible/group_vars/servers/versions.yml#L2-L3)
- [ ] PUBLISH: Update the link to the latest minor branch on [doc.owncloud.com](https://gitea.owncloud.services/devops/websites/src/branch/master/ansible/roles/docs/templates/config.j2)
- [ ] PUBLISH: publish Linux packages - @crrodriguez
	- [ ] Check CE Linux build projects at obs.int & https://download.owncloud.org/download/repositories/ - @crrodriguez
	- [ ] Repo info to portal.owncloud.com - @crrodriguez
	- [ ] Forward "packages ready" to eng + release-coordination mailing lists and channel - @crrodriguez
- [ ] BUILD, PUBLISH: Create [docker images](https://confluence.owncloud.com/display/OG/Creating+Docker+Image)
	- [ ] Setup demo instance for marketing screenshots.
- [ ] PUBLISH: Update maintenance and release schedule on customer.owncloud.com and https://github.com/owncloud/core/wiki/Maintenance-and-Release-Schedule - @pmaier1

- [ ] COMMUNICATION: Announce release readiness on eng + release-coordination mailing lists (no central post here, done below!)
- [ ] COMMUNICATION: Handover in marketing channel, links, versions, demo instance.  @jnweiger, @HanaGemela, @frankaellen
	- [ ] Input for Customer Mailing: Main features, security fixes & advisories - @pmaier1, @corby, @frankaellen
- [ ] COMMUNICATION: All communications coordinated by marketing team. - @frankaellen
	- [ ] Update download links on website. - @frankaellen
		- [ ] Version number, release date - @frankaellen
		- [ ] Is there both, a complete and a minimal package? - @frankaellen
		- [ ] TAR md5, sha256, asc (full + minimal) - @frankaellen
		- [ ] ZIP md5, sha256, asc (full + minimal) - @frankaellen
		- [ ] ESX appliance
		- [ ] Virtual Box appliance
		- [ ] QCOW 2 appliance
		- [ ] VMWare appliance

	- [ ] Wikipedia + Wikidata update (de+en) - @frankaellen
	- [ ] Blogpost about release - @frankaellen
	- [ ] Social Media communications: Facebook, LinkedIn, Twitter - @frankaellen
		- [ ] (_optional_) hackernews, reddit - @frankaellen

	- [ ] Enterprise: Customer Mailing - @frankaellen
	- [ ] Website update feature table - @frankaellen
	- [ ] Webinar 1-2 weeks after announcement - @frankaellen, @pmaier1
	- [ ] Internal demo for ownCloud employees - @frankaellen, @pmaier1
	
- [ ] COMMUNICATION: Release announcement on Central based on the blog entry [Category News, Tag server](https://central.owncloud.org/tags/c/news/server) - @jnweiger, @HanaGemela

- [ ] PUBLISH: Adjust [web update server] to deliver releases and test - @VicDeo, @davitol
	- [ ] Adjust web updater config - @VicDeo
		- [ ] Point web update server "production/stable" channels for stable releases - @VicDeo
		- [ ] Point the "beta" to the latest stable if there is no new beta/RC - @VicDeo
		- [ ] QA: test PR - @davitol
	- [ ] PUBLISH: Deploy [web update server] to deliver releases - @crrodriguez

- [ ] APPLIANCE: release previous version of appliance
	- [ ] [PR to owncloud-docker/appliance](https://github.com/owncloud-docker/appliance/pull/24/) - @voroyam
	- [ ] DOC: put the appliance process into [handbook](https://confluence.owncloud.com/display/OG/Release+Processes)- @voroyam @jnweiger
	- [ ] send appliance to univention for review - @voroyam

## Post-Release Phase

- [ ] Schedule a retrospective call
- [ ] DEV: Close GitHub project
- [ ] Ensure that the [release template](https://github.com/owncloud/handbook/edit/master/modules/ROOT/examples/releases/server_release_template.md) is up to date
- [ ] Close remaining items in GitHub Release project board
